#!/bin/bash
 
if [[ $1 && $2 ]]
then
    filename=$(basename "$1")
    filename=${filename%.*}
    directory=$(dirname "$1")
    targetBasename=$(basename "$2")
    targetDirectory=$(dirname "$2")
    

    echo "Generating thumbnail"
    ffmpeg -i "$1"  -filter:v yadif -ss 0.5 -t 1 -f image2 -frames:v 1 "$targetDirectory/$targetBasename"
    echo "Finished thumbnail"



 
    echo "All Done!"
else
    echo "Usage: [filename] [targetFilename]"
fi


